server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://stg-host:3306/stgdb
    username: stg_user
    password: stg_password

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true