server:
  port: 8083

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  application:
    name: main-microservice
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/gymdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

application:
  security:
    jwt:
      secret-key: 1EYjx0tlp3TGOvaxIrMci+DfkJtYxdxvbFDSG+5f6DHBfQAWDb+D8nd09wJy3zp/c+vn6aTezbJWxwSI2N/AzNIuxdXtHvEEok0JQDaqHQpccwFVqk1iMkcHoxxtepSgLK7PUBmUlGP/JxZ3gH+qi/fB2CtoV1tzAYTl1HH0KbkpFAKu/MnxphIbBBlZqxQSC3w+v25QmsNNmaISOVAEhfZRjzkxbhkwF0Y8s9e+ocQM/6nVtofrAGNnRbyOTkSY6EgV8pn5giJW6DwI0W5G09srRNs5d1nWrPzNjOKRw9UFbg/LkJvFRcaf2X+T8lE1iZCrag4k7ZP7b8+P8gp6MqXhQRXCsY921ex560uvcd4=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ # Replace with the actual Eureka server URL. Make sure it's the same one specified in the secondary microservice's configuration
#    register-with-eureka: true
#    fetch-registry: true

#report-microservice:
#  url: http://localhost:8087


