server:
  port: 8087

spring:
  application:
    name: report-microservice
  datasource:
    url: jdbc:h2:mem:reportdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdatabase